### ISSUE TITLE
Make ETH/DAI the default pair

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#12]

**Comment by gbalabasquer** [comment]
@pimato It is already the current default pair. However once you change it, it keeps the chosen one saved in localstorage.

**Comment by peculiarity** [comment]
Well you shouldn't have this ;)

**Comment by gbalabasquer** [comment]
Mmm don't agree. I think is annoying to have to select always the same pair if the user wants to buy in different chunks. But up to you.

**Comment by pimato** [comment]
for single collateral DAI we are going to have ETH/MKR as default pair. As soon as we are going to move to multi collateral DAI we are going to switch to ETH/DAI.

**Comment by peculiarity** [comment]
@pimato , You told me to put ETH / DAI as default pair

**Comment by gbalabasquer** [comment]
@pimato which pair are we making finally as default? ETH/DAI is still the actual pair.

**Comment by pimato** [comment]
ETH/DAI is set as a default pair.
