### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by peculiarity** [OasisDEX/oasis-direct#13]
Migrate the landing page from the oasis-direct application to the base one.
Integrate the widget in there

**Comment by gbalabasquer** [comment]
@peculiarity So the landing page will be directly in the application project?

**Comment by peculiarity** [comment]
![image](https://user-images.githubusercontent.com/23715025/35089843-5d996c9c-fc38-11e7-8f94-dee80ed7c150.png)
