### ISSUE TITLE
Inputfields should not get emptied after a user clicked on the switch icon or picked another currency

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#14]

**Comment by gbalabasquer** [comment]
@pimato 
Mmm but which behavior you would use in this case?
Let's put some examples:
1) I'm selling 1 ETH for DAI, a DAI value shows up. Then change DAI to MKR. This case I think is quite straight forward. I can imagine the MKR value will be calculated.
2)  I'm selling 1 ETH for DAI, a DAI value shows up. Then change ETH to MKR. Should I calculate selling 1 MKR and get the DAI value, or keep the DAI value and get how much MKR do we need?
3) I'm selling 1 ETH for DAI, a DAI value shows up. Then we switch the coins, should we keep 1 ETH buying or the DAI amount as selling?

I think is even more complicate to decide when you are selecting the buy amount.
So we should put a simple rule to do always the same or specify case by case what we want to do.
I'm not sure if there is a natural way to decide, that is why I've opted to clean the inputs, so the user never gets confused.

**Comment by peculiarity** [comment]
IMO the clearing should happen on every change. Person might forget what he intended to do  and might forget to change the value. Calculating some scenarios just complicates everything. I don't see the problem with providing values on token change

**Comment by gbalabasquer** [comment]
@pimato @peculiarity As we discussed with Thomas, we are leaving this issue on hold for now.

**Comment by pimato** [comment]
closed until it will be necessary to open it up again.
