### ISSUE TITLE
Input placeholder appears even when there is a value

### ISSUE THREAD

**Issue by peculiarity** [OasisDEX/oasis-direct#16]
1. `receive amount` input field should have value ( calculated based on the `deposit amount` input )
2. click on the mouse inside the `receive amount` input field
3. click anywhere else outside of the `receive amount` input field
4. `RECEIVE AMOUNT` placeholder appears for couple of seconds instead of the number value.

![image](https://user-images.githubusercontent.com/23715025/31880105-db600908-b7df-11e7-8de1-84ed63c7906b.png)

**Disclaimer**: In the following example I don't have sufficient amount to fulfill the order but I've tested it with `deposit amount` I can fulfill and the behavior is the same.

**Comment by deepinit-arek** [comment]
This is problem with the contracts rewrite. not an UI code issue
