### ISSUE TITLE
widget redesign v2

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#21]
I have updated the recent oasis.direct design mockup with the help of the team feedback:

![oasis-direct-v2](https://user-images.githubusercontent.com/5337809/35276718-99146bc2-0044-11e8-8484-f9f65128898e.png)

**changes**:

- legal agreement information box with checkbox added
- replaced order information from the bottom to the top
- added token description to the picker
- changed the price to show the base/quote currency
- renamed "fee" to simple "gas cost" 
- changed the widget size to 470 w 420 h

**Comment by pimato** [comment]
### Oasis.direct idle mode

![oasis-direct-starter-idle](https://user-images.githubusercontent.com/5337809/35276825-ff12ca04-0044-11e8-86e2-fdd1e7f986be.png)

**Measurements**: [oasis-direct-widget-old.zip](https://github.com/OasisDEX/oasis-direct-base/files/1655958/oasis-direct-widget-old.zip)

# Update

![o1](https://user-images.githubusercontent.com/5337809/36192538-38f2daa6-1162-11e8-9b64-f92878eaf920.png)

**Measurements**: [o1.zip](https://github.com/OasisDEX/oasis-direct-base/files/1723044/o1.zip)

**Comment by pimato** [comment]
### Oasis.direct inputfield defined

![oasis-direct-starter-2](https://user-images.githubusercontent.com/5337809/35276905-4ca0df72-0045-11e8-867d-faee957d8c98.png)

**Measurements**: [oasis-direct-widget-2.zip](https://github.com/OasisDEX/oasis-direct-base/files/1655967/oasis-direct-widget-2.zip)

# Update

![o2](https://user-images.githubusercontent.com/5337809/36192596-84fb5a86-1162-11e8-948d-e8e06591ee1d.png)

**Measurements:** [o2.zip](https://github.com/OasisDEX/oasis-direct-base/files/1723049/o2.zip)

**Comment by pimato** [comment]
Oasis.direct Order details entered

![oasis-direct-starter-3](https://user-images.githubusercontent.com/5337809/35277046-b1b6c9da-0045-11e8-891e-f88db931f63f.png)

**Measurements**: [oasis-direct-widget-3.zip](https://github.com/OasisDEX/oasis-direct-base/files/1655974/oasis-direct-widget-3.zip)

# Update

![o3](https://user-images.githubusercontent.com/5337809/36192651-c72aa5ec-1162-11e8-94d9-44f6cad70f17.png)

**Measurements:** [o3.zip](https://github.com/OasisDEX/oasis-direct-base/files/1723055/o3.zip)

**Comment by dbrock** [comment]
Looks great.

I think "DEPOSIT AMOUNT" and "RECEIVE AMOUNT" need to be lighter or the user won't understand that they are supposed to click there to type their own text. (I think a similar problem exists in the current Oasis UI.) I might move those labels out of the inputs boxes altogether and put them above the boxes instead, since otherwise once you start typing and the labels disappear you might be confused about which token you are buying and which you are selling.

**Comment by gbalabasquer** [comment]
@pimato maybe we should include what gas price we are using for the gas cost.

**Comment by peculiarity** [comment]
@pimato  All of those are implemented

**Comment by pimato** [comment]
@dbrock thanks a lot for your input, I will have a look if I can change the inputs.

@gbalabasquer can we tell metamask what gas price we want to have?

@peculiarity awesome, I am going to push the new finalized trade design out

**Comment by pimato** [comment]
### Finalized Trade Step 1

![fin1](https://user-images.githubusercontent.com/5337809/35433380-8a4842e4-0283-11e8-95fe-8287d6a0f044.png)

Measurements: [fin1.zip](https://github.com/OasisDEX/oasis-direct-base/files/1667266/fin1.zip)
Icon pack: [icon_pack.zip](https://github.com/OasisDEX/oasis-direct-base/files/1667277/icon_pack.zip)

**Comment by pimato** [comment]
### Finalized Trade Step 2

![fin2](https://user-images.githubusercontent.com/5337809/35433601-5ad8aa16-0284-11e8-9dba-8a52e783fd4b.png)

Measurements: [fin2.zip](https://github.com/OasisDEX/oasis-direct-base/files/1667281/fin2.zip)

**Comment by pimato** [comment]
### Finalized Trade 3
![fin3](https://user-images.githubusercontent.com/5337809/35433762-d9f4f868-0284-11e8-87c2-99970e3f8ce8.png)

**new Measurements:**  [oasis-direct-widget-old.zip](https://github.com/OasisDEX/oasis-direct-base/files/1715549/oasis-direct-widget-old.zip)


## UPDATE

![last](https://user-images.githubusercontent.com/5337809/36139728-00127a02-109f-11e8-94b5-03c4a267451b.png)

- new icon
- different paddings in the congratulation box

**Measurements**: [oasis-final.zip](https://github.com/OasisDEX/oasis-direct-base/files/1719161/oasis-final.zip)
**new Icon**: [icon-green-tick.svg.zip](https://github.com/OasisDEX/oasis-direct-base/files/1719370/icon-green-tick.svg.zip)

**Comment by pimato** [comment]
**Oasis.direct Picker Page v2**

![oasis-direct-picker](https://user-images.githubusercontent.com/5337809/35871966-e8e3326a-0b65-11e8-9687-343d887adeda.png)

**changes**:

- slider added
- bigger currency boxes
- balances added

**Measurements**: [oasis-direct-widget-old.zip](https://github.com/OasisDEX/oasis-direct-base/files/1699961/oasis-direct-widget-old.zip)

**Close Icon**: [icon-close.svg.zip](https://github.com/OasisDEX/oasis-direct-base/files/1700030/icon-close.svg.zip)

**Comment by peculiarity** [comment]
@pimato  you should be able to see it on https://oasis-direct.surge.sh

**Comment by pimato** [comment]
I took the time to update the not connected page with the new dimensions of the widget:

![oasis-not-connected](https://user-images.githubusercontent.com/5337809/36091981-0606fe42-0fe6-11e8-8676-61d05ce28d9a.png)

**Measurements**: [oasis-not-connected.zip](https://github.com/OasisDEX/oasis-direct-base/files/1716007/oasis-not-connected.zip)

## UPDATE

![oasis-direct-others copy](https://user-images.githubusercontent.com/5337809/36143197-b65cd87e-10aa-11e8-8b89-f35a02dc3d54.png)

**Measurements**: [oasis-direct-widget-old 2.zip](https://github.com/OasisDEX/oasis-direct-base/files/1719394/oasis-direct-widget-old.2.zip)

**Comment by pimato** [comment]
With the no connected page, there is also the need to update the metamask locked page:

![oasis-metamask](https://user-images.githubusercontent.com/5337809/36093426-eb92fe08-0fea-11e8-83ca-15b31026fe0f.png)

**Measurements**: [oasis-metamask.zip](https://github.com/OasisDEX/oasis-direct-base/files/1716037/oasis-metamask.zip)

**Comment by pimato** [comment]
if our contracts can`t provide that much liquidity, the frontend needs to display it:

![o4](https://user-images.githubusercontent.com/5337809/36192730-2634aace-1163-11e8-9435-030c5d96cc7e.png)

**Measurements**: [o4.zip](https://github.com/OasisDEX/oasis-direct-base/files/1723061/o4.zip)

**Comment by pimato** [comment]
Sometimes It can happen that the trades will fail, so we need inform the user why it can happen:

![oasis-direct-fail](https://user-images.githubusercontent.com/5337809/36374389-7393152e-156b-11e8-9b96-770435c001fe.png)

Measurements: [oasis-direct-widget-fail2.zip](https://github.com/OasisDEX/oasis-direct-base/files/1736396/oasis-direct-widget-fail2.zip)


Icon: [ic_remove_circle_black_24px.svg.zip](https://github.com/OasisDEX/oasis-direct-base/files/1736361/ic_remove_circle_black_24px.svg.zip)

**Comment by pimato** [comment]
Insufficient funds page:

![ins](https://user-images.githubusercontent.com/5337809/36416321-0a53a7a4-1629-11e8-8b3e-d660814a80f3.png)

**Measurements**: [insufficient-funds.zip](https://github.com/OasisDEX/oasis-direct-base/files/1739518/insufficient-funds.zip)
