### ISSUE TITLE
Oasis.direct landing page design mockup

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#22]
![mobile](https://user-images.githubusercontent.com/5337809/35329940-e5f62cd8-0101-11e8-8652-0e92a1e2be1b.png)

**Measurements**:  [oasis-direct-landing-mobile.zip](https://github.com/OasisDEX/oasis-direct-base/files/1659614/oasis-direct-landing-mobile.zip)

**Comment by peculiarity** [comment]
@pimato  Can you please provide breaking point / breaking points so that I know when to apply the page layout?

**Comment by pimato** [comment]
I have a few issues:

**checkbox**:
- after switching pairs, the disclaimer checkbox is still activated
- checkbox is taking too much time to load, should be much quicker
- checkbox position not aligned with the design mockup

**asset picker**:
- assets are listed from top to bottom with one asset per row instead of two in one row

**Comment by pimato** [comment]
widget starter issues:

**shadow inside the inputfield**

![img_2ac5ac730b92-1](https://user-images.githubusercontent.com/5337809/35803734-22400aac-0a75-11e8-9a10-3ac214868d41.jpeg)

**Comment by pimato** [comment]
Hey guys, I ´ve started to work on an optimized desktop landing-page design:

![landing-desktop](https://user-images.githubusercontent.com/5337809/36369199-a6785780-155a-11e8-8d67-a437ddc5c08a.png)

Measurements: [ld.zip](https://github.com/OasisDEX/oasis-direct-base/files/1736015/ld.zip)
Icon: [icon-fail.svg.zip](https://github.com/OasisDEX/oasis-direct-base/files/1736785/icon-fail.svg.zip)

links for the footer: 

Documentation : `http://developer.makerdao.com/`
Oasisdex.com: `https://oasisdex.com`
Chat: `chat.makerdao.com`
Reddit: `https://www.reddit.com/r/MakerDAO/`
Oasis twitter : `https://twitter.com/oasisdex`
Oasis Steem: `will be added soon`
