### ISSUE TITLE
metamask version 3.13.7 is introducing errors

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#23]
<img width="469" alt="bildschirmfoto 2018-01-25 um 11 39 38" src="https://user-images.githubusercontent.com/5337809/35384070-73032546-01c4-11e8-8e19-d0983ceda915.png">

**Comment by peculiarity** [comment]
@pimato Dan and Aaron from Metamask are working on this. As far as I checked this morning, the fix should be released today. https://github.com/MetaMask/metamask-extension/issues/3104#event-1447014395

**Comment by pimato** [comment]
fixed
