### ISSUE TITLE
every token should have a defined minimum value for trading

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#24]
While testing oasis.direct on the mobile ethereum client `cypher` I am realising that it doesn`t make sense to give the user the possibility to exchange 0,0001 DAI. We need to define a min value for each token which is traded on oasis.direct.

For the first release we are going to have tokens with min value:

- ETH `0,03 ETH`
- MKR `0,03 MKR`
- DAI `30 DAI`

**Comment by gbalabasquer** [comment]
@pimato it's done

**Comment by gbalabasquer** [comment]
As I've mentioned in chat values are set much lower now for testing purposes.
