### ISSUE TITLE
while clicking on the switching button sometimes the name of the right asset is getting selected

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#28]
<img width="504" alt="bildschirmfoto 2018-02-13 um 13 14 36" src="https://user-images.githubusercontent.com/5337809/36149414-dc4fae0c-10bf-11e8-806f-b4dc1a0bc859.png">

**Comment by peculiarity** [comment]
Come on this is ridiculous. This has nothing to do with the code or implementation. This is  when you click too many times and the browser selects element to highlight. It's not even selecting. THIS is not an issue

Go to makerdao.com  and start click on top of the Dai work from the title of the hero image. I will start selecting the text.

Start clicking exactly abovce your issue content and it will select...
![image](https://user-images.githubusercontent.com/23715025/36169820-a89cb5d0-10fd-11e8-9ed6-0daeeae7b5a4.png)
