### ISSUE TITLE
button border wrong color

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#29]
current:

<img width="616" alt="bildschirmfoto 2018-02-13 um 13 18 40" src="https://user-images.githubusercontent.com/5337809/36149559-7790420a-10c0-11e8-914f-399a86cb72a1.png">

should:

<img width="733" alt="bildschirmfoto 2018-02-13 um 13 19 18" src="https://user-images.githubusercontent.com/5337809/36149569-82576920-10c0-11e8-8b06-2be07ceb31ec.png">

bg: #448AFF
border: #3E7BE6

**Comment by peculiarity** [comment]
@pimato Done
