### ISSUE TITLE
Landing page - Adding Navigation

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#32]
![landing-v2](https://user-images.githubusercontent.com/5337809/36777505-fbf77a54-1c69-11e8-92e7-db8c57f067ea.png)

**Changes**:
- Adding Navigation for the Tax Exporter and Exchange

**Measurements**: [od-landing-v2.zip](https://github.com/OasisDEX/oasis-direct-base/files/1766253/od-landing-v2.zip)

**Comment by peculiarity** [comment]
Done in https://github.com/OasisDEX/oasis-direct-base/commit/066ae49b15e8a5f5634d647d5ab8716b68e14479
