### ISSUE TITLE
When selling 0.03 ETH worth of MKR transaction fails with misleading MM comment

### ISSUE THREAD

**Issue by luke7211** [OasisDEX/oasis-direct#39]
When you trade MKR-ETH and type 0.03 in the ETH box the MKR amount is below 0.03. Transaction will fail but with a very misleading error messagage leading user to believe that 1% threshold has been broken. This is repeatable.

![image](https://user-images.githubusercontent.com/30408726/38111148-2bdb9746-339e-11e8-85f5-eb7493c9abb7.png)

**Comment by luke7211** [comment]
The fix is obvious, what is more worrying to me is that there is a:
1. Totally unintuitive message from MetaMask. Clearly sth went wrong and we did not catch it beforehand
2. Even more troubling "Failed transaction probably due to exceeding 1% threshold" message - is there any way to differentiate that situation from other errors ?

**Comment by arkadiuszsz** [comment]
@luke7211 The really relevant part in MM message is the `Transaction Error`.
So when we do not allow situation where transaction would fail during gas estimation we should be on safe side (as far i can tell ).

**Comment by luke7211** [comment]
@deepinit-arek If there is an error during gas estimation the MM window should not pup up at all as we should have seen this error before. Why our gasEstimation() did not fail, but MM failed () ?

**Comment by arkadiuszsz** [comment]
@luke7211 I think You are right. Ill try to have closer look at this.

**Comment by gbalabasquer** [comment]
Need to review it in detail, but the minimum value is just an UI limit, a transaction failure has nothing to do with this limit.
