### ISSUE TITLE
Remove popup which appears if someone clicks on balances

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#4]
Remove popup events : 

<img width="544" alt="bildschirmfoto 2018-01-16 um 15 56 05" src="https://user-images.githubusercontent.com/5337809/34995146-e9f70e10-fad5-11e7-9775-de795b562c70.png">

**Comment by gbalabasquer** [comment]
@pimato do you still the copy functionality or I remove all of that?

**Comment by pimato** [comment]
@gbalabasquer remove from now, the popup is too aggressive.
