### ISSUE TITLE
currency picker button and inputfields are not properly aligned 

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#5]
<img width="427" alt="bildschirmfoto 2018-01-16 um 15 58 21" src="https://user-images.githubusercontent.com/5337809/34995242-2843b574-fad6-11e7-9e25-cf544a457f40.png">

**Comment by gbalabasquer** [comment]
@pimato this is fixed in the actual version. If you still see any alignment problem please re-open.
