### ISSUE TITLE
Market System Warning message not properly styled

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-direct#6]
Currently: 

<img width="540" alt="bildschirmfoto 2018-01-16 um 16 09 00" src="https://user-images.githubusercontent.com/5337809/34995725-a242d9f8-fad7-11e7-9ab8-05c97f57d6ab.png">

should look like:

![oasis-direct-starter](https://user-images.githubusercontent.com/5337809/34995976-74c9ea6a-fad8-11e7-8752-1359fcee4bfd.png)

**Comment by gbalabasquer** [comment]
@pimato are we sure we don't want to show this message in red?
I mean the design you sent but font, icon and border red?
I know it is not a user error, but still the user should read it immediately. I don't know, just personal opinion.

**Comment by peculiarity** [comment]
@pimato please elaborate on this one

**Comment by pimato** [comment]
In my view, red is way too aggressiv for this kind of information message. This kind of message will show up quite some time so we don`t want to show a red message all the time to the user who is not responsible for it.

I think with the disabling of the "Start Transaction"-Button with the combination of the calm grey message, we are not confronting the user too much and he/she are not afraid to test another type of trade maybe. @gbalabasquer @peculiarity

**Comment by gbalabasquer** [comment]
@peculiarity @pimato
Ok I get the point, let's do that.
